name: docker-crosstool-ng

on:
  push:
    branches:
    - '*'
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron:  "0 */8 * * *"
  workflow_dispatch:

jobs:
  image:
    name: build image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["alpine", "debian", "ubuntu"]
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v3.0.0
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "🛠️ Docker QEMU"
        run: make qemu
      - name: "🛠️ Build and 📤 Upload to hub.docker.com"
        run: |
#            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
            make ${{ matrix.version }}
      - name: "🧹 Clean"
        run: make clean
      